"""
Django settings for BookMyBox project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import warnings
from datetime import timedelta
from pathlib import Path

import dj_database_url
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


def env(key, default=None, required=False):
    """Helper to fetch environment variables with explicit required handling."""
    value = os.getenv(key, default)
    if required and value is None:
        raise ImproperlyConfigured(f"Environment variable {key} is required.")
    return value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = env('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Lightweight guard against accidentally deploying with DEBUG=True: warn (not
# hard-crash, so local dev workflows aren't disrupted) if DEBUG is on and
# ALLOWED_HOSTS contains anything that doesn't look like a local dev host.
if DEBUG and any(
    host not in ('localhost', '127.0.0.1', '0.0.0.0', '') for host in ALLOWED_HOSTS
):
    warnings.warn(
        "DEBUG=True with a non-local ALLOWED_HOSTS entry — this looks like a "
        "production deployment running with debug mode on. Set DEBUG=False "
        "before deploying.",
        RuntimeWarning,
    )

# Production-only security hardening. These stay inert in local development
# (DEBUG=True) so plain http://localhost workflows aren't broken by forced
# HTTPS redirects or secure-only cookies.
if not DEBUG:
    # This app is always deployed behind a reverse proxy (nginx in
    # docker-compose.prod.yml, or an equivalent in front of it) that talks
    # plain HTTP to Daphne — Django's own connection is never "secure" by
    # itself. Without telling Django which header carries the proxy's real
    # scheme, SECURE_SSL_REDIRECT below 301-redirects every single request
    # to https, including ones that arrived as http with nothing behind
    # them terminating TLS: a redirect loop / dead end. Trust the proxy's
    # X-Forwarded-Proto instead (nginx sets this from its own $scheme, so
    # it correctly reflects whether TLS was actually terminated upstream).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Defaults on (secure-by-default for a "real" production deploy sitting
    # behind a TLS-terminating load balancer/ingress). docker-compose.prod.yml
    # ships no TLS termination of its own (that needs a real domain + cert,
    # out of scope here — see DEPLOYMENT.md), so its .env.docker explicitly
    # sets this to False; a deployment that does add TLS in front of it
    # should leave this at its default True.
    SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600  # start conservative; raise once HTTPS is confirmed stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_BROWSER_XSS_FILTER = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'daphne',  # must precede django.contrib.staticfiles per Channels docs, so it can hijack runserver
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_extensions',
    'django_filters',
    'user',
    'user_profile',
    'boxes',
    'bookings',
    'owner_dashboard',
    'user_dashboard',
    'chatbot',
    'rewards',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BookMyBox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BookMyBox.wsgi.application'
# ASGI is now the primary application (Channels/WebSocket support for the
# slot reservation feature); WSGI is kept for tooling (e.g. collectstatic)
# that still expects it.
ASGI_APPLICATION = 'BookMyBox.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL drives this: e.g. "postgresql://user:pass@host:5432/dbname" for
# production, or the default sqlite URL below for zero-config local development.
#
# DB_CONN_MAX_AGE defaults to Django's old "persistent connections" value
# (600s), but under Daphne/ASGI each concurrent request can end up opening
# its own connection rather than sharing one the way a single-threaded WSGI
# worker would — a stress test against docker-compose.prod.yml's default
# Postgres (max_connections=100) reproducibly exhausted every connection
# slot under ~30-50 concurrent DB-touching requests, and because the stale
# connections don't expire for 600s, the outage didn't self-heal even after
# load stopped (not even `psql` could connect). Set DB_CONN_MAX_AGE=0 (or a
# low value) for deployments on constrained/default-tuned Postgres like this
# one, so connections close after each request instead of accumulating; a
# real fix at higher scale is a pooler (PgBouncer) in front of Postgres.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(env('DB_CONN_MAX_AGE', '600')),
    )
}

# Tests that deliberately hammer one row with many concurrent threads (see
# bookings/tests/test_reserve_confirm_flow.py's 50-thread concurrency proof)
# expose two SQLite-only limitations, neither of which apply to Postgres
# (the production database, see DEPLOYMENT.md — MVCC + row-level locking
# doesn't have either problem):
#   1. A longer busy-timeout so genuinely queued writers get to retry
#      instead of failing immediately.
#   2. Django's default SQLite *test* database is an in-memory, shared-cache
#      DB, which uses SQLite's shared-cache table-level locking — that
#      raises SQLITE_LOCKED (not SQLITE_BUSY) on lock conflicts between
#      threads, and SQLITE_LOCKED is explicitly NOT retried by the
#      busy-timeout/busy-handler mechanism (a SQLite behavior, not a Django
#      or Python bug). Pointing the test DB at a real file instead of
#      :memory: avoids shared-cache mode entirely, so ordinary file-level
#      locking (which *does* honor the timeout below) applies instead.
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {}).setdefault('timeout', 30)
    DATABASES['default'].setdefault('TEST', {}).setdefault('NAME', str(BASE_DIR / 'test_db.sqlite3'))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# whitenoise serves static files directly from the Django process — no
# separate static file server needed for a first production deploy. Run
# `python manage.py collectstatic` before starting the app in production.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Increased to show all boxes without pagination issues

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']

}

# JWT Configuration
# Long-lived by design: the frontend silently refreshes the access token on
# any 401 (see api.jsx's response interceptor), and ROTATE_REFRESH_TOKENS
# issues a fresh REFRESH_TOKEN_LIFETIME window on every refresh — so a user
# who opens the app at least once every 90 days never has to log in again.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in env('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173').split(',')
    if origin.strip()
]

CORS_ALLOW_ALL_ORIGINS = False  # Never enable in production
CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be sent
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Demo Credentials for development - only available when DEBUG is True
DEMO_CREDENTIALS = {
    'user': {
        'email': 'user@demo.com',
        'name': 'Demo User',
        'phone': '1234567890',
        'role': 'user'
    },
    'owner': {
        'email': 'owner@demo.com',
        'name': 'Demo Owner',
        'phone': '1234567891',
        'role': 'owner',
        'business_name': 'Demo Sports Center'
    },
    'admin': {
        'email': 'admin@demo.com',
        'name': 'Demo Admin',
        'phone': '1234567892',
        'role': 'admin'
    }
} if DEBUG else {}

AUTH_USER_MODEL = 'user.User'

# Google OAuth Client ID used to verify ID tokens from the frontend
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', '')

# Google Gemini API key for the chatbot
GEMINI_API_KEY = env('GEMINI_API_KEY', '')

# Resend (transactional email) — used for password-reset and booking-invite
# emails (see BookMyBox/emailing.py). Left blank in dev: send_email() logs
# instead of raising, so local dev works without an account.
RESEND_API_KEY = env('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')

# Base URL of the frontend SPA, used to build links embedded in emails
# (password reset, booking invites) — never derived from request.get_host()
# since those emails are sent from a Celery worker with no request context.
FRONTEND_URL = env('FRONTEND_URL', 'http://localhost:5173')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redis is now real infrastructure (added for the slot reservation/wait-queue
# feature), so the cache backend upgrades from FileBasedCache to RedisCache —
# this was already anticipated by the comment that used to live here.
# One physical Redis instance, split by logical DB index so cache eviction,
# pub/sub channel-layer traffic, Celery broker traffic, and reservation
# hold/queue state (bookings/reservation.py) can never collide with each other:
#   /0 cache   /1 channel layer   /2 celery broker+results   /3 reservation state
REDIS_URL = env('REDIS_URL', 'redis://localhost:6379')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'{REDIS_URL}/0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [f'{REDIS_URL}/1'],
        },
    },
}

# Celery — used to schedule one-shot hold-expiry checks for the slot
# reservation queue (bookings/tasks.py). No periodic/beat schedule needed;
# each hold schedules its own single apply_async(eta=...) check.
CELERY_BROKER_URL = env('CELERY_BROKER_URL', f'{REDIS_URL}/2')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', f'{REDIS_URL}/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Beat schedule — this app only ever scheduled one-shot eta= tasks before
# (bookings/tasks.py's hold-expiry cascade), never a recurring job, so a
# `celery beat` process wasn't running at all. mark-completed-bookings is
# what actually flips a past-dated Confirmed booking to Completed (nothing
# else in the codebase does this) — cashback/scratch-card/spin-wheel grants
# all hang off that transition. run-scheduled-payouts is added by the
# per-owner-per-sport commission + scheduled payouts feature.
CELERY_BEAT_SCHEDULE = {
    'mark-completed-bookings': {
        'task': 'bookings.tasks.mark_completed_bookings_task',
        'schedule': crontab(minute=0),  # hourly
    },
    'run-scheduled-payouts': {
        'task': 'owner_dashboard.tasks.run_scheduled_payouts_task',
        'schedule': crontab(hour=2, minute=0),  # daily, 2am
    },
}

# Default platform commission percent (as a fraction, e.g. 0.10 = 10%) used
# when an owner/sport has no CommissionRate override — see
# boxes/pricing.py::resolve_commission_rate(). Replaces what used to be a
# hardcoded 0.1 literal in three separate files.
DEFAULT_COMMISSION_RATE = float(env('DEFAULT_COMMISSION_RATE', '0.10'))

# Dedicated logical DB for reservation hold/queue state (bookings/reservation.py) —
# kept separate from the Django cache DB so cache eviction policy can never
# touch reservation keys.
REDIS_RESERVATION_URL = env('REDIS_RESERVATION_URL', f'{REDIS_URL}/3')

# How long a user who reaches the front of a contended slot has to confirm
# their booking before the hold is released to the next person in the queue.
RESERVATION_HOLD_TTL_SECONDS = int(env('RESERVATION_HOLD_TTL_SECONDS', '300'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# your_project/settings.py

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "My Project Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "My Project",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "My Project",

    # Logo to use for your site, must be present in static files, used for login form
    # "site_logo": "images/logo.png", # Example path

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the My Project Admin",

    # Copyright on the footer
    "copyright": "My Project Ltd",

    # The model admin to search from the search bar, search model admin has to be defined in your project
    "search_model": "user.User",

    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "user.User"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "boxes"},
    ],
   "theme": "darkly", # e.g., "cerulean", "flatly", "sandstone", "united"
    "theme": "flatly",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
}
