# Generated by Django 5.2.4 on 2026-08-01 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_payment_status'),
        ('boxes', '0006_alter_box_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_status__in', ['Confirmed', 'Completed'])), fields=('box', 'date', 'start_time'), name='unique_active_booking_per_box_date_start'),
        ),
    ]
