# Generated by Django 5.2.4 on 2026-08-11 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_cancellation_reason_booking_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('online', 'Online'), ('owner_manual', 'Owner (walk-in/manual)')], default='online', help_text='Whether a customer booked this online, or the box owner created it directly (walk-in/manual).', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who actually created this row — the booking customer for an online booking, or the box owner for a manual/walk-in one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
