# Generated by Django 5.2.4 on 2026-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_source_booking_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recurring_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Links sibling occurrences of the same recurring-booking request — null for a one-off booking.', null=True),
        ),
    ]
