# Generated by Django 5.2.4 on 2026-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_bookinginvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cashback_credited_at',
            field=models.DateTimeField(blank=True, help_text='Set once rewards.services.apply_cashback() has credited this booking — guards against double-crediting.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of total_amount paid via wallet balance at checkout. Does not reduce total_amount — owner revenue/commission is still computed off the full price.', max_digits=10),
        ),
    ]
