# Generated by Django 5.2.4 on 2026-08-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_cashback_credited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_date',
            field=models.DateField(blank=True, help_text="The booking's date before its one allowed reschedule — null until rescheduled. Only ever set once, so a booking's true original slot survives even though only one reschedule is allowed in total.", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_start_time',
            field=models.CharField(blank=True, default='', help_text="Companion to original_date — the booking's start_time before its one allowed reschedule.", max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, help_text="Set the first (and only — see bookings/services.py::reschedule_booking, one reschedule per booking) time this booking's date/start_time is changed. Presence of a value is what gates the frontend's Reschedule action from being offered again.", null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No-show', 'No-show')], default='Confirmed', max_length=50),
        ),
    ]
