/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as VenuesVenueIdRouteImport } from './routes/venues.$venueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/$venueId',
  path: '/$venueId',
  getParentRoute: () => VenuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/owner': typeof OwnerRoute
  '/venues': typeof VenuesRouteWithChildren
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/owner': typeof OwnerRoute
  '/venues': typeof VenuesRouteWithChildren
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/owner': typeof OwnerRoute
  '/venues': typeof VenuesRouteWithChildren
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/owner'
    | '/venues'
    | '/booking/$bookingId'
    | '/venues/$venueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/owner'
    | '/venues'
    | '/booking/$bookingId'
    | '/venues/$venueId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/owner'
    | '/venues'
    | '/booking/$bookingId'
    | '/venues/$venueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  OwnerRoute: typeof OwnerRoute
  VenuesRoute: typeof VenuesRouteWithChildren
  BookingBookingIdRoute: typeof BookingBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof VenuesRoute
    }
  }
}

interface VenuesRouteChildren {
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
}

const VenuesRouteChildren: VenuesRouteChildren = {
  VenuesVenueIdRoute: VenuesVenueIdRoute,
}

const VenuesRouteWithChildren =
  VenuesRoute._addFileChildren(VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  OwnerRoute: OwnerRoute,
  VenuesRoute: VenuesRouteWithChildren,
  BookingBookingIdRoute: BookingBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
