# Generated by Django 5.2.4 on 2026-08-15 03:58
# Scoped to OwnerVerification only — depends on 0005_adminactionlog (a
# parallel change) so the two new models don't collide in one migration file.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_adminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('gst_number', models.CharField(blank=True, default='', max_length=20)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='owner_verification_docs/')),
                ('verification_status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_verifications',
            },
        ),
    ]
