# Generated by Django 5.2.4 on 2026-08-15 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_ownerverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPayoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=34)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_payout_details',
            },
        ),
    ]
