# Generated by Django 5.2.4 on 2026-08-15 08:04

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_ownerpayoutdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerverification',
            name='verification_document',
            field=models.FileField(blank=True, help_text='PAN card, GST certificate, or similar — PDF/JPG/PNG only, up to 10MB.', null=True, upload_to='owner_verification_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), user.models.validate_verification_document_size]),
        ),
    ]
