# Generated by Django 5.2.4 on 2026-07-31 16:35

from django.conf import settings
from django.db import migrations, models


def deduplicate_reviews(apps, schema_editor):
    """Remove duplicate reviews so only the most recent review per user/box remains."""
    Review = apps.get_model('boxes', 'Review')
    duplicates = Review.objects.values('box_id', 'user_id').annotate(
        count=models.Count('id')
    ).filter(count__gt=1)

    for dup in duplicates:
        review_ids = list(
            Review.objects.filter(
                box_id=dup['box_id'], user_id=dup['user_id']
            ).order_by('-date', '-id').values_list('id', flat=True)
        )
        # Keep the most recent, delete the rest
        if len(review_ids) > 1:
            Review.objects.filter(id__in=review_ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_box_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_reviews, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('box', 'user'), name='unique_review_per_user_box'),
        ),
    ]
