# Generated by Django 5.2.4 on 2026-08-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_review_unique_review_per_user_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The approval status of the box.', max_length=10),
        ),
    ]
