# Generated by Django 5.2.4 on 2026-08-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_alter_box_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='closing_time',
            field=models.CharField(default='23:00', help_text='Daily closing time (HH:MM, 24-hour)', max_length=5),
        ),
        migrations.AddField(
            model_name='box',
            name='opening_time',
            field=models.CharField(default='06:00', help_text='Daily opening time (HH:MM, 24-hour)', max_length=5),
        ),
    ]
