# Generated by Django 5.2.4 on 2026-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_box_closing_time_box_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
