# Generated by Django 5.2.4 on 2026-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_review_owner_response_review_owner_response_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', help_text='The approval status of the box.', max_length=20),
        ),
    ]
