# Generated by Django 5.2.4 on 2026-08-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_alter_box_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Relative storage paths of up to 4 review photos.'),
        ),
    ]
