# Generated by Django 5.2.4 on 2026-08-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0011_blockeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('weekday', 'Weekdays (Mon-Fri)'), ('weekend', 'Weekends (Sat-Sun)'), ('all', 'Every day')], max_length=10)),
                ('start_time', models.CharField(help_text='HH:MM, 24-hour', max_length=5)),
                ('end_time', models.CharField(help_text='HH:MM, 24-hour', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='boxes.box')),
            ],
            options={
                'ordering': ['applies_to', 'start_time'],
            },
        ),
    ]
