# Generated by Django 5.2.4 on 2026-08-15 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0015_alter_box_capacity_alter_box_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformcommissionsetting',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AddField(
            model_name='platformcommissionsetting',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
