# Generated by Django 5.2.4 on 2026-08-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0016_alter_platformcommissionsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrate',
            options={'ordering': ['-effective_from', '-id']},
        ),
        migrations.AlterModelOptions(
            name='platformcommissionsetting',
            options={'ordering': ['-effective_from', '-id']},
        ),
    ]
