# Generated by Django 5.2.4 on 2026-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0017_alter_commissionrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='google_maps_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
