# Generated by Django 5.2.4 on 2026-08-12 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', help_text="'scheduled' rows are auto-created by run_scheduled_payouts_task (owner_dashboard/tasks.py).", max_length=10),
        ),
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday..6=Sunday. Used when frequency is weekly/biweekly.', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-28. Used when frequency is monthly.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
