# Generated by Django 5.2.4 on 2026-08-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_dashboard', '0002_payout_source_payoutschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
