# Generated by Django 5.2.4 on 2026-08-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('cashback', 'Cashback'), ('scratch_card', 'Scratch card win'), ('spin_wheel', 'Spin wheel win'), ('redeem_code', 'Redeemed code'), ('booking_payment', 'Applied to booking'), ('admin_adjustment', 'Admin adjustment'), ('refund', 'Booking cancellation refund')], max_length=20),
        ),
    ]
