# Generated by Django 5.2.4 on 2026-08-13 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0013_commissionrate'),
        ('rewards', '0002_alter_wallettransaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='box',
            field=models.ForeignKey(blank=True, help_text='Null = admin-issued, platform-wide wallet credit. Set = owner-issued, redeemable only at checkout for this specific box.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeem_codes', to='boxes.box'),
        ),
        migrations.CreateModel(
            name='OwnerScratchCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_card_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScratchCardAutoGrantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
